    templates:
      tvshows:
        exists_series:
          - /home/pi/Videos/series/
          - /home/pi/Downloads/incomplete
        regexp:
          reject:
            - FASTSUB
            - VOSTFR
            - Subtitulado
        content_filter:
          reject:
            - '*.rar'
            - '*.zip'
            - '*.avi'  
        transmission:
          host: localhost
          port: 9091
          username: YOUR_TRANSMISSION_USER
          password: 'YOUR_TRANSMISSION_PASSWD'
          path: /home/pi/Videos/series/{{series_name|pathscrub}}/S{{"%02d"|format(series_season)}}  
        inputs:
          - rss: http://showrss.info/user/YOUR_SHOWRSS_USER_ID.rss?magnets=true&namespaces=true&name=null&quality=hd&re=null
      movies_template:
        transmission:
          host: localhost
          port: 9091
          username: YOUR_TRANSMISSION_USER
          password: 'YOUR_TRANSMISSION_PASSWD'
          path: /home/pi/Videos/peliculas
        regexp:
            reject:
                - german
                - sweden
                - italian
                - hindi
     
    tasks:
      watchlist:
        priority: 1
        trakt_list:  # You can also use imdb_list
          account: YOUR_TRAKT_USERNAME
          list: watchlist
          type: movies
        accept_all: yes
        seen: local  # We don't want accepted movies on this feed to affect actual download feed
        list_add:
          - movie_list: watchlist  # you can call this whatever you want

    # task that automatically downloads movies from the movie_list
      movies search:
        trakt_lookup: yes  # can also use imdb_lookup or tmdb_lookup
        priority: 10 # run after the movie queue fill task
        discover:
          what:
            - movie_list: watchlist
          from:
            - piratebay: yes
            - rarbg:
                category: x264 1080p
          interval: 1 days
        torrent_alive: 10 # Will reject results with less than 10 seeds
        quality: 1080p # Make sure no screeners or cams are downloaded
        list_match:
          from:
            - movie_list: watchlist
        transmission:
          host: localhost
          port: 9091
          username: YOUR_TRANSMISSION_USER
          password: 'YOUR_TRANSMISSION_PASSWD'
          path: /home/pi/Videos/peliculas

      get_tvshowshd:
        priority: 1
        template: tvshows
        configure_series:
          from:
            trakt_list:
              username: YOUR_TRAKT_USERNAME
              list: Following in HD
              type: shows
              account: YOUR_TRAKT_USERNAME
          settings:
            quality: 720p hdtv
     
      get_tvshows:
        priority: 2
        template: tvshows
        configure_series:
          from:
            trakt_list:
              username: YOUR_TRAKT_USERNAME
              list: Following
              type: shows
              account: YOUR_TRAKT_USERNAME
          settings:
            quality: hdtv

      fill_movie_queue:
        priority: 3
        trakt_list:
          username: YOUR_TRAKT_USERNAME
          type: movies
          list: watchlist
          account: YOUR_TRAKT_USERNAME
        seen: local
        accept_all: yes
        movie_list: movies from trakt
 
      cleanup:
        priority: 6
        clean_transmission:
          host: localhost
          port: 9091
          username: YOUR_TRANSMISSION_USER
          password: 'YOUR_TRANSMISSION_PASSWD'
          finished_for: 7 days
